#
# Martin Jerry US‑SS01 (WB2S/BK72xx) Fan‑domain variant for better HA adoption
#
# Purpose
#   This config is functionally identical to the switch version but exposes a native
#   Home Assistant Fan entity (domain: fan) for better UX, icons, and automation fit.
#   The physical relay is the same; the fan entity simply mirrors ON/OFF to the relay.
#
# Hardware pin map (US‑SS01 WB2S reference)
#   Relay:        P8   (active HIGH)
#   Blue LED:     P26  (active LOW, inverted) mirrors relay state
#   Red  LED:     P24  (active LOW, inverted) blinks when Wi‑Fi is disconnected
#   Button:       P10  (input + pullup, active LOW)
#
# Secrets you MUST provide yourself
#   wifi_ssid and wifi_password are referenced with !secret below and must be defined
#   by you in your ESPHome/Home Assistant secrets.yaml. Example:
#     wifi_ssid: "MyHomeWiFi"
#     wifi_password: "super_secret_password"
#   If you do not use secrets, replace the !secret lines with literal strings.
#
# Behavior & reliability
#   logger.baud_rate is 0 to avoid serial logging overhead on BK chips.
#   api.reboot_timeout and wifi.reboot_timeout ensure self‑recovery after long outages.
#   preferences.flash_write_interval minimizes flash wear (10 minutes).
#   Wi‑Fi power saving is disabled (power_save_mode: NONE) for responsiveness.
#   Button toggles the fan entity; the relay follows the fan state.
#
# Adoption via ESPHome Dashboard
#   Add/update the dashboard_import URL below to your public GitHub file so the device
#   can be discovered and adopted from the ESPHome Dashboard.
#
substitutions:
  name: "mj-us-ss01-fan"
  friendly_name: "Martin Jerry US-SS01 Fan (WB2S)"
  device_description: "Martin Jerry US-SS01 WiFi fan"
  project_name: "Martin_Jerry.US_SS01_FAN"
  project_version: "v1.1.2"
  log_level: "INFO"
  ipv6_enable: false
  icon: "mdi:fan"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: "${device_description}"
  name_add_mac_suffix: true
  min_version: 2025.9.3
  project:
    name: "${project_name}"
    version: "${project_version}"

bk72xx:
  board: wb2s

preferences:
  flash_write_interval: 10min

logger:
  level: ${log_level}
  baud_rate: 0

api:
  reboot_timeout: 15min

ota:
  - platform: esphome

web_server:
  port: 80

network:
  enable_ipv6: ${ipv6_enable}

wifi:
  ap: {}

  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      bssid: !secret wifi_bssid
  fast_connect: true

  power_save_mode: NONE
  reboot_timeout: 15min

  on_disconnect:
    - switch.turn_on: red_led_blink
  on_connect:
    - switch.turn_off: red_led_blink

mdns:
  disabled: false

captive_portal:

# Allow adoption/import directly from GitHub
dashboard_import:
  package_import_url: "github://PavelMikeev/ESPHome/martin-jerry-us-ss01-wb2s-fan.yaml@main"
  import_full_config: true

switch:
  - platform: gpio
    id: relay
    name: "Fan Switch"
    icon: "${icon}"
    pin: P8
    internal: true
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    pin: P26
    inverted: true
    internal: true

  - platform: gpio
    id: red_led
    pin: P24
    inverted: true
    internal: true

  - platform: template
    id: red_led_blink
    internal: true
    lambda: |-
      return false;
    turn_on_action:
      - while:
          condition:
            not:
              wifi.connected:
          then:
            - switch.turn_on: red_led
            - delay: 500ms
            - switch.turn_off: red_led
            - delay: 500ms
    turn_off_action:
      - switch.turn_off: red_led

binary_sensor:
  - platform: gpio
    id: main_button
    pin:
      number: P10
      mode:
        input: true
        pullup: true
      inverted: true
    internal: true
    filters:
      - delayed_on: 12ms
      - delayed_off: 12ms
    on_press:
      - fan.toggle: fan_entity

fan:
  - platform: template
    name: "Fan"
    id: fan_entity
    icon: "mdi:fan"
    on_turn_on:
      - switch.turn_on: relay
    on_turn_off:
      - switch.turn_off: relay

button:
  - platform: restart
    id: restart_button
    name: "Restart"
    entity_category: config

  - platform: factory_reset
    name: "Factory Reset"
    entity_category: config

sensor:
  - platform: uptime
    id: uptime_seconds
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal dB"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: template
    name: "Firmware Version"
    icon: mdi:chip
    entity_category: diagnostic
    lambda: |-
      return std::string("${project_version}");

  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic

  - platform: template
    name: "Uptime"
    icon: mdi:clock-start
    entity_category: diagnostic
    disabled_by_default: true
    update_interval: 1min
    lambda: |-
      uint32_t s = (uint32_t) id(uptime_seconds).state;
      if (s == 0 || s > 315576000U) {
        return {"Starting up"};
      }
      uint32_t d = s / 86400U; s %= 86400U;
      uint8_t  h = s / 3600U; s %= 3600U;
      uint8_t  m = s / 60U;
      char buf[40];
      if (d)       snprintf(buf, sizeof(buf), "%ud %uh %um", (unsigned)d, h, m);
      else if (h)  snprintf(buf, sizeof(buf), "%uh %um", h, m);
      else         snprintf(buf, sizeof(buf), "%um", m);
      return std::string(buf);

  - platform: wifi_info
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    mac_address:
      name: "MAC Address"
      entity_category: diagnostic
